name = "rxz"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.133.223.51:2096"
UUID = "4c9aa090-9eee-40d7-b0f3-5114f1770150"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
