name = "rxz666"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "158.101.215.216:443"
UUID = "e315ecd9-cd9f-4104-a468-a0769c5d9672"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
